services:
  nifi:
    image: apache/nifi:2.0.0-M1
    volumes:
      - nifi_conf:/opt/nifi/nifi-current/conf
      - nifi_extensions:/opt/nifi/nifi-current/extensions
      - nifi_database_repository:/opt/nifi/nifi-current/database_repository
      - nifi_flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - nifi_content_repository:/opt/nifi/nifi-current/content_repository
      - nifi_provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - nifi_state:/opt/nifi/nifi-current/state
      - nifi_logs:/opt/nifi/nifi-current/logs
      - ./nifi-starter-nar/target:/opt/nifi/nifi-current/nar_extensions
    ports:
      - 8443:8443
    environment:
      NIFI_WEB_HTTPS_HOST: nifi
      NIFI_WEB_HTTPS_PORT: 8443
      NIFI_ZK_CONNECT_STRING: zookeeper:2181
      NIFI_ELECTION_MAX_WAIT: 10 sec
      NIFI_SENSITIVE_PROPS_KEY: my-random-string
      NIFI_CLUSTER_NODE_PROTOCOL_PORT: 8082
      SINGLE_USER_CREDENTIALS_USERNAME: nifi
      SINGLE_USER_CREDENTIALS_PASSWORD: nifinifinifinifi
      NIFI_SECURITY_USER_AUTHORIZER: single-user-authorizer
      NIFI_SECURITY_USER_LOGIN_IDENTITY_PROVIDER: single-user-provider
      INITIAL_ADMIN_IDENTITY: CN=admin
      NODE_IDENTITY: CN=nifi-0, OU=NIFI

volumes:
  nifi_conf:
  nifi_extensions:
  nifi_database_repository:
  nifi_flowfile_repository:
  nifi_content_repository:
  nifi_provenance_repository:
  nifi_state:
  nifi_logs:
